{{- if .Values.opendkim.enabled }}
{{- range $v := .Values.opendkim.domains }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "postfix.fullname" $ }}-{{ $v.domain | replace "." "-" }}"
type: Opaque
data:
  dkim_private_key: |-
    {{ $v.private_key | b64enc }}
{{- end }}
{{- end }}
