image:
  repository: ghcr.io/tinkerstation/containers/postfix
  pullPolicy: IfNotPresent
  tag: 1.0-3.6.5
imagePullSecrets: []
  #  - name: docker-config

# list of username and password for mailserver access
auth: []
  # - username:
  #   password:

network:
  loadBalancerIP:
  # allow source ip ranges
  allowedIPRange:
  domain:

postfix:
  # max message size in bytes
  messageSizeLimit: "30720000"
  # for sender and receiver email address
  # permits use of alphabets, digits and the special characters - and _
  allowedEmailPattern: |-
      /^[a-zA-Z0-9\.\-\_]+@[a-zA-Z0-9\.\-\_]+\.[a-zA-Z0-9]+$/ PERMIT
      !/^[a-zA-Z0-9\.\-\_]+@[a-zA-Z0-9\.\-\_]+\.[a-zA-Z0-9]+$/ REJECT
  # extra postfix config
  # values can be separated with commas, carriage return and space 
  config:

networkPolicy:
  enabled: false
  egressToKubeDNSEnabled: false
  egressToGoogleDNSEnabled: false
  ingress: []
  # - cidr: 
  #     - 0.0.0.0/0
  #   ports:
  #     - port: 25
  #       protocol: TCP
  egress: []
  # - cidr: 
  #     - 0.0.0.0/0
  #   ports:
  #     - port: 25
  #       protocol: TCP

opendkim:
  enabled: false
  domains:
    # provision them in this way
    # - domain: 
    # subdomain i.e mail.tinkerstation.com
    #   selector: mail 
    #   private_key: ""
  SigningTable: ""
  TrustedHosts: "" 
  KeyTable: ""
  conf: |-
    Syslog                  yes
    SyslogSuccess           yes
    RequireSafeKeys         false
    Canonicalization        relaxed/simple
    Mode                    sv
    # SubDomains            yes
    OversignHeaders         From
    UserID                  opendkim
    # Required to use local socket with MTAs that access the socket as a non-\n
    # privileged user (e.g. Postfix)\n
    UMask                   0002
    Socket                  inet:8891@localhost
    PidFile                 /var/run/opendkim/opendkim.pid
    TrustAnchorFile         /usr/share/dns/root.key
    KeyTable                /etc/opendkim/KeyTable
    SigningTable            refile:/etc/opendkim/SigningTable
    ExternalIgnoreList      refile:/etc/opendkim/TrustedHosts
    InternalHosts           refile:/etc/opendkim/TrustedHosts
  supervisord_service: |-
    [supervisord]
    nodaemon=true
    loglevel=info

    [program:opendkim]
    command=opendkim -x /etc/opendkim.conf -f -p inet:8891@localhost
    autostart=true
    autorestart=true
    stderr_logfile=/var/log/opendkim.err.log
    stdout_logfile=/var/log/opendkim.out.log
